services:
  nextcloud:
    image: nextcloud:latest
    container_name: zemi_nextcloud
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - nextcloud_data:/var/www/html
      - /Users/zemi/ZemiV1/docker/nextcloud/ssl:/etc/ssl/nextcloud
    environment:
      - NEXTCLOUD_ADMIN_USER=zemi
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_password
      - NEXTCLOUD_TRUSTED_DOMAINS=100.111.133.70
    restart: unless-stopped

volumes:
  nextcloud_data:
